# Generated by Django 3.0.6 on 2020-05-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200528_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredpost',
            name='image',
            field=models.ImageField(default='default/featured-post.jpg', upload_to='featured_post_images/'),
        ),
    ]
