# Generated by Django 3.0.6 on 2020-05-28 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200528_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredpost',
            name='title',
        ),
    ]
