# Generated by Django 3.0.6 on 2020-05-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200528_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_photo',
            field=models.FileField(blank=True, null=True, upload_to='cover_pics'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
